apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zestful-partridge-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zestful-partridge-python 
  name: zestful-partridge-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zestful-partridge-python 
